service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  # profile:
  region: us-west-1
  stage: dev

plugins:
  - serverless-offline

functions:
  hello:
    handler: src/helloworld.handler

    
